name: Create GitHub Release

on:
  push:
    tags:
      - "v*" # Same trigger, on tags

permissions:
  contents: write # Needed to create GitHub Release

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Upload dist files to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
