name: Publish to PyPI

on:
  push:
    tags:
      - "v*" # Trigger on version tags like v1.0.0

permissions:
  id-token: write # Needed for PyPI OIDC token
  contents: read # Basic read permission

jobs:
  publish-pypi:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - run: |
          python -m pip install --upgrade pip
          pip install build

      - run: python -m build

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
